title: Plasma Support
description: Plasma Support
baseurl: "/"
url: "https://incplasma.github.io"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs
